src/objects/OwnFiledsComparator__c.object
<CustomObject>
    <fields>
        <fullName>first__c</fullName>
        <label>first</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>reason__c</fullName>
        <label>reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>second__c</fullName>
        <label>second</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OwnFiledsComparator</label>
    <nameField>
        <label>Comparator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OwnFiledsComparators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ShowDifferenceController.cls
/**
 * Created by new on 06.07.2017.
 */

public with sharing class ShowDifferenceController {
    public OwnFiledsComparator__c difference = new OwnFiledsComparator__c();
    public Double first{get;set;}
    public Double second{get;set;}
    public String reason{get;set;}
    public Boolean vis{get;set;}

    public ShowDifferenceController(){
        //difference = [SELECT first__c, second__c, reason__c From OwnFiledsComparator__c Limit 1];

    }
    //public
    public void getDif(){

        if (first != null && second != null){
            if(first> second){
                reason = 'first>second';
                vis = true;
            }
            else if(first < second){
                reason = 'first<second';
                vis = true;
            }
            else{
                reason = 'equal';
                vis = false;
            }
        }
        System.debug(vis);
        //return reason;
    }
    public void save(){
        System.debug(difference);
        difference.name = 'name';
        difference.first__c = first;
        difference.second__c = second;
        difference.reason__c = reason;
        upsert difference;
    }

}